### ISSUE TITLE
panic when reading configuration

### ISSUE THREAD

**Issue by mffrench** [hyperledger-labs/fabric-smart-client#117]
on branch fabric_v2.2.1 (golang 1.14 + viper v1.1) when reading fsc node config, I get following panic: 

```
...
2021-09-06 11:38:16.883 UTC [fabric-sdk] Install -> INFO 019 Set Fabric Network Service Provider
2021/09/06 11:38:16 Start triggered panic: interface conversion: interface {} is map[string]interface {}, not map[interface {}]interface {}
goroutine 8 [running]:
runtime/debug.Stack(0xc0002d3930, 0x21c60c0, 0xc0005043f0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xab
github.com/hyperledger-labs/fabric-smart-client/pkg/node.(*node).Start.func1(0xc0002d3ec0, 0xc00073b5c0)
	/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20210819140749-c135df0d6750/pkg/node/node.go:76 +0x84
panic(0x21c60c0, 0xc0005043f0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/hyperledger-labs/fabric-smart-client/platform/fabric/core.NewConfig(0x2906b60, 0xc000502530, 0x7f9c85241c10, 0xc0003a8be0, 0xc00073b5c0)
	/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20210819140749-c135df0d6750/platform/fabric/core/config.go:29 +0x8a6
github.com/hyperledger-labs/fabric-smart-client/platform/fabric/sdk.(*p).Install(0xc0003af360, 0x0, 0x0)
	/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20210819140749-c135df0d6750/platform/fabric/sdk/sdk.go:59 +0x356
github.com/hyperledger-labs/fabric-smart-client/pkg/node.(*node).Start(0xc00073b5c0, 0x0, 0x0)
	/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20210819140749-c135df0d6750/pkg/node/node.go:86 +0x1ae
...
```

we had to apply following patch to overcome the panic (fabric_v2.2.1 branch) : 

```
diff --git a/platform/fabric/core/config.go b/platform/fabric/core/config.go
index 4a5cc32..3834a00 100644
--- a/platform/fabric/core/config.go
+++ b/platform/fabric/core/config.go
@@ -26,15 +26,14 @@ func NewConfig(configProvider ConfigProvider) (*Config, error) {
 	if err := configProvider.UnmarshalKey("fabric", &value); err != nil {
 		return nil, errors.Wrap(err, "failed unmarshalling `fabric` key")
 	}
-	m := value.(map[interface{}]interface{})
+	m := value.(map[string]interface{})
 	var names []string
 	var defaultName string
-	for k, v := range m {
-		name := k.(string)
+	for name, v := range m {
 		if strings.ToLower(name) != "enabled" {
 			names = append(names, name)
 			// is this default?
-			defaultValue, ok := (v.(map[interface{}]interface{}))["default"]
+			defaultValue, ok := (v.(map[string]interface{}))["default"]
 			if ok && defaultValue.(bool) {
 				if len(defaultName) != 0 {
 					logger.Warnf("only one network should be set as default, ignoring [%s], default is set to [%s]", name, defaultValue)
```

**Comment by mffrench** [comment]
solve on branch fabric_v2.2.1 with PR https://github.com/hyperledger-labs/fabric-smart-client/pull/118. We look after our golang migration to 1.16 if we reproduce same issue...

**Comment by adecaro** [comment]
@mffrench do we still need this?

**Comment by mffrench** [comment]
This is no more required. Working on main with no changes needed :)
