### ISSUE TITLE
Weaver relay sample, trying to send message larger than max Error 

### ISSUE THREAD

**Issue by corthDfine** [hyperledger-labs/fabric-smart-client#529]
I am getting the following error when trying to run the weaver relay sample:

```  
[e][fabric.alpha-peer-lifecycle-chaincode-install] Error: failed to endorse chaincode install: rpc error: code = ResourceExhausted desc = trying to send message larger than max (3245316333 vs. 104857600)
panic: No future change is possible.  Bailing out early after 21.876s.
Expected
    <int>: 1
to match exit code:
    <int>: 0

goroutine 1 [running]:
github.com/hyperledger-labs/fabric-smart-client/integration.failMe({0xc0003fe080?, 0x12?}, {0xc0008692a0?, 0x3?, 0x3?})
        /fabric-smart-client/integration/integration.go:341 +0x2d
github.com/onsi/gomega/internal.(*AsyncAssertion).match.func3({0x13e2cb6, 0x30})
        /go/pkg/mod/github.com/onsi/gomega@v1.27.8/internal/async_assertion.go:478 +0x1d3
github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc000170000, {0x15bcd50?, 0xc00070a168}, 0x1, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/onsi/gomega@v1.27.8/internal/async_assertion.go:527 +0xf78
github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc000170000, {0x15bcd50, 0xc00070a168}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/onsi/gomega@v1.27.8/internal/async_assertion.go:145 +0x8d
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.InstallChaincode(0xc0005ad340, 0xc0004536c0, {0xc000520458, 0x1, 0x0?})
        /fabric-smart-client/integration/nwo/fabric/network/deploy.go:74 +0xf3
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.PackageAndInstallChaincode(0xc0005ad340, 0xc0004536c0, {0xc000520458, 0x1, 0x1})
        /fabric-smart-client/integration/nwo/fabric/network/deploy.go:46 +0x293
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.(*Network).DeployChaincode(0xc0005ad340, 0xc0004536c0)
        /fabric-smart-client/integration/nwo/fabric/network/network.go:272 +0x3e5
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.(*Network).PostRun(0xc0005ad340, 0x0)
        /fabric-smart-client/integration/nwo/fabric/network/network.go:239 +0x38e
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric.(*Platform).PostRun(0xc000015958, 0x0)
        /fabric-smart-client/integration/nwo/fabric/platform.go:152 +0x8b
github.com/hyperledger-labs/fabric-smart-client/integration/nwo.(*NWO).Start(0xc0002036b0)
        /fabric-smart-client/integration/nwo/nwo.go:127 +0x7e4
github.com/hyperledger-labs/fabric-smart-client/integration.(*Infrastructure).Start(...)
        /fabric-smart-client/integration/integration.go:185
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd/network.Start(0x0?)
        /fabric-smart-client/integration/nwo/cmd/network/cmd.go:191 +0x233
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd/network.StartCmd.func1(0xc000228600?, {0xc00077be40?, 0x2?, 0x2?})
        /fabric-smart-client/integration/nwo/cmd/network/cmd.go:149 +0x56
github.com/spf13/cobra.(*Command).execute(0xc000228600, {0xc00077be20, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004f00)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd.(*Main).Execute(0xc00087f920)
        /fabric-smart-client/integration/nwo/cmd/main.go:57 +0x20c
main.main()
        /fabric-smart-client/samples/fabric/weaver/relay/relay.go:21 +0x114
```

To reach this point, I simply followed the instructions from the readme of that sample.
I can see that the issue is that the filesize of the chaincode is too large (it is actually 3 GB in size) while only 100 MB are allowed. I can fix it by increasing the RPC limit, but I have the feeling that something else is going wrong here.

Can you please have a look?

I am getting a likewise error when running the IOU sample.

**Comment by adecaro** [comment]
Hi @corthDfine , this happened to me in the past when my local branch contains some leftover of previous integration tests execution. I would suggest you to check `git status` to identify if any non-tracked file is there in your branch. In case, remove them and retry 🤞
